name: deep-neuro-fuzzy
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - pip
  - pip:
      - torch
      - shap
      - lime
      - xgboost
      - -e .[dev]
